
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('brand_size').del()
    .then(function () {
      // Inserts seed entries
      return knex('brand_size').insert([
        {
          id: 1,
          brand: "Nike",
          size: "small",
          chest_in: 36.25,
          waist_in: 30.5,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 2,
          brand: "Nike",
          size: "medium",
          chest_in: 39.25,
          waist_in: 33.5,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 3,
          brand: "Nike",
          size: "large",
          chest_in: 42.5,
          waist_in: 36.5,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 4,
          brand: "Nike",
          size: "extra large",
          chest_in: 46.25,
          waist_in: 40.5,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 5,
          brand: "Nike",
          size: "extra extra large",
          chest_in: 51,
          waist_in: 38.75,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 6,
          brand: 2,
          size: "extra small",
          chest_in: 36,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 7,
          brand: 2,
          size: "small",
          chest_in: 38,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 8,
          brand: 2,
          size: "medium",
          chest_in: 40,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 9,
          brand: 2,
          size: "large",
          chest_in: 42,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 10,
          brand: 2,
          size: "extra large",
          chest_in: 44,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 11,
          brand: 2,
          size: "extra extra large",
          chest_in: 46,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 12,
          brand: 2,
          size: "extra small",
          chest_in: 36,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 13,
          brand: 2,
          size: "small",
          chest_in: 38,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 14,
          brand: 2,
          size: "medium",
          chest_in: 40,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 15,
          brand: 2,
          size: "large",
          chest_in: 42,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 16,
          brand: 2,
          size: "extra large",
          chest_in: 44,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
        {
          id: 17,
          brand: 2,
          size: "extra extra large",
          chest_in: 46,
          waist_in: null,
          inseam_in: null,
          neck_in: null,
          shoe_size_cm: null,
        },
      ]);
    });
};
